version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - epoxy_sqlite_data:/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  epoxy_sqlite_data:
